#!/usr/bin/env bash
#
# creates a drill hierarchy, where each level of the hierarchy
# can be rotated by incrementing the leading zeros
#

source drills.lib

# shorthand
EF="finger=p,r,m,i"
ES="string=1,2,3,4"
ESDS="string=1,2,3,4,12,23,34"
MFT="bowpos=middle,frog,top"
MFTZ="$MFT,travelling"
XING_VARS="$ES reptop=off,on npb=0,1,2,3 $MFTZ" # shoulder/elbow/wrist

# build the drill hierarchy
mkdir violin; cd violin
mkdir 1.quiz
mkdir 2.tuning
drill 3.intonation retuning
drill 3.intonation pitch-singing 
drill 3.intonation pitch-matching timing=after,together,before
drill 3.intonation pitch-hitting
drill 3.intonation interval-singing
drill 3.intonation interval-matching timing=after,together,before
drill 3.intonation interval-recognition
drill 3.intonation interval-hitting
drill 3.intonation predictive-scales
drill 3.intonation double-stop-matching

# bow hold
drill 4.bow-arm jellyfish
drill 4.bow-arm itsy-bitsy-spider
drill 4.bow-arm windscreen-wiper
drill 4.bow-arm bow-hand-resets
drill 4.bow-arm horizontal-bow-raises
drill 4.bow-arm vertical-bow-raises

# bow placement
drill 4.bow-arm square $MFT $ESDS
drill 4.bow-arm swivel-and-stop $MFT $ES
drill 4.bow-arm hops $MFTZ
drill 4.bow-arm retakes dir=u,d $MFTZ
drill 4.bow-arm pizzicato

# bow pressure
drill 4.bow-arm bow-benders $ESDS
drill 4.bow-arm one-minute-bows $ESDS
drill 4.bow-arm even-bowing $ESDS spb=2,4,8,15
drill 4.bow-arm frog-reversed $ESDS spb=2,4,8,15
drill 4.bow-arm finger-lifting $ESDS spb=2,4,8,15
drill 4.bow-arm pinky-and-index $ESDS spb=2,4,8,15
drill 4.bow-arm air-bowing spb=4,8,15 bow=normal,reversed
drill 4.bow-arm parlando $ESDS xpb=1,2,4 first=light,heavy
drill 4.bow-arm dynamics $ESDS crescendo,decrescendo,pianissimo

# bow changes
drill 4.bow-arm stationary $ESDS $MFT
drill 4.bow-arm detache $ESDS $MFTZ rhythms
drill 4.bow-arm legato $ESDS $MFTZ rhythms
drill 4.bow-arm martele $ESDS $MFTZ
drill 4.bow-arm stacatto $ESDS $MFTZ
drill 4.bow-arm brushing $ESDS $MFTZ
drill 4.bow-arm spicatto $ESDS $MFTZ
drill 4.bow-arm colle $ESDS

# bow acceleration
drill 4.bow-arm fast-bowing $ESDS rest=1,0 bps=1,2
drill 4.bow-arm speed-changes $ESDS xpb=1,2,3 first=slow,fast

# bow direction
drill 4.bow-arm overbowing
drill 4.bow-arm snaking xpb=1,2,3
drill 4.bow-arm lane-changes lanes=121,232,123,321
drill 4.bow-arm tilt-flat-tilt $ES

# string crossings
drill 4.bow-arm single $XING_VARS num=2,3,4
drill 4.bow-arm double $XING_VARS
drill 4.bow-arm triple $XING_VARS
drill 4.bow-arm chords $XING_VARS pat=1-23,12-3,12-23,12-24

# violin hold
drill 5.pitch-arm no-hand-swivels
drill 5.pitch-arm pinky-reaches

# finger independence
drill 5.pitch-arm finger-wiggles straight,curled
drill 5.pitch-arm fingertip-kisses
drill 5.pitch-arm finger-position-jankin
drill 5.pitch-arm finger-position-curls
drill 5.pitch-arm finger-hammers

# finger dropping
drill 5.pitch-arm trills fingers=01,12,23,34,13,24,14 $ES pos=1,3,5,7,9,Z
drill 5.pitch-arm half-scales shape=westside,chicken,gun,porcupine $ES drone=off,on
drill 5.pitch-arm fifth-hops $EF $ES
drill 5.pitch-arm double-stop-trills $ES thirds
drill 5.pitch-arm drop-and-lift-to-harmonic $EF $ES

# vibrato
drill 5.pitch-arm vibrato-knocking fulcrum=wrist,arm loc=air,in-situ silent,voiced
drill 5.pitch-arm on-the-body-vibrato fulcrum=wrist,arm $EF
drill 5.pitch-arm vibrato-slides fulcrum=wrist,arm $ES silent,voiced
drill 5.pitch-arm on-the-string fulcrum=wrist,arm silent,voiced $EF $ES pos=1,3,5,7,9,Z

# shifts
drill 5.pitch-arm one-finger-scales chromatic,major,minor
drill 5.pitch-arm same-finger-shifts $EF int=1,2,3,4,5,6,7,8,9,X,Y,Z pos=1,3,5,7,9,Z
drill 5.pitch-arm different-finger-shifts $EF int=1,2,3,4,5,6,7,8,9,X,Y,Z pos=1,3,5,7,9,Z

# scales
SCALE_VARS="tempo=30,60,90,120,240 seq=ud,climb,fours,random-walk,random-jump npb=1,2,3,4,5,6,7 octaves=1,2,3 pos=1,3,5,7,9,Z"
drill 6.both-arms chromatic-scale $SCALE_VARS
drill 6.both-arms scale-jake $SCALE_VARS
drill 6.both-arms arpeggio-jake $SCALE_VARS
drill 6.both-arms scale-elwood $SCALE_VARS
drill 6.both-arms arpeggio-elwood $SCALE_VARS
drill 6.both-arms scale-pistol $SCALE_VARS
drill 6.both-arms arpeggio-pistol $SCALE_VARS
drill 6.both-arms scale-nuke $SCALE_VARS
drill 6.both-arms arpeggio-nuke $SCALE_VARS
drill 6.both-arms scale-explosion $SCALE_VARS
drill 6.both-arms arpeggio-explosion $SCALE_VARS
drill 6.both-arms scale-chicken $SCALE_VARS
drill 6.both-arms arpeggio-chicken $SCALE_VARS
drill 6.both-arms scale-dinosaur $SCALE_VARS
drill 6.both-arms arpeggio-dinosaur $SCALE_VARS

mkdir 7.phrases
mkdir 8.etudes
mkdir 9.playlist

#chord patterns {301} {es} {3-strings/12, 3-strings/22} {ud} {fmt}
#right hand pizzicato

