#!/bin/bash

source make-patterns

DIR=$OUTDIR/pitches
mkdir -p $DIR

STEPS=-20
for PITCH in 24 25 26 27 28 29 2X 2Y 30 31 32 33 34 35 36 37 38 39 3X 3Y 40 41 42 43 44 45 46 47 48 49 4X 4Y 50 51 52 53 54 55 56; do
  echo "
    X:0
    M:1/1
    L:1/1
    Q:120
    K:C transpose=$STEPS
    %%MIDI program 00
    |C|" \
      | abc2midi /dev/stdin -o /dev/stdout \
      | timidity - -A800 --output-24bit --output-mode=w --output-file=- \
      | ffmpeg -i - -ac 1 $DIR/${PITCH}.mp3

  STEPS=$((STEPS+1))
done

