#!/usr/bin/env bash
#
# creates a drill hierarchy, where each level of the hierarchy
# can be rotated by incrementing the leading zeros
#

source drills.lib

# shorthand
EF="finger=p,r,m,i"
ES="string=1,2,3,4"
ESDS="string=1,2,3,4,12,23,34"
MFT="bowpos=middle,frog,top"
MFTZ="$MFT,travelling"
XING_VARS="$ES reptop=off,on npb=0,1,2,3 $MFTZ" # shoulder/elbow/wrist
SCALE_VARS="tempo=30,60,90,120,240 seq=ud,climb,fours,random-walk,random-jump npb=1,2,3,4,5,6,7 pos=1,3,5,7,9,Z"
FRETS=2

# build the drill hierarchy
mcd violin
mkdir 1.quiz
mkdir 2.tuning

mcd 3.intonation
drill retuning
drill pitch-singing 
drill pitch-matching timing=after,together,before
drill pitch-hitting
drill interval-singing
drill interval-matching timing=after,together,before
drill interval-recognition
drill interval-hitting
drill predictive-scales
drill double-stop-matching

# bow hold
cd ..
mcd 4.bow-arm
drill jellyfish
drill itsy-bitsy-spider
drill windscreen-wiper
drill bow-hand-resets
drill horizontal-bow-raises
drill vertical-bow-raises

# bow placement
drill square $MFT $ESDS
drill swivel-and-stop $MFT $ES
drill hops $MFTZ
drill retakes dir=u,d $MFTZ
drill pizzicato

# bow pressure
drill bow-benders $ESDS
drill one-minute-bows $ESDS
drill even-bowing $ESDS spb=2,4,8,15
drill frog-reversed $ESDS spb=2,4,8,15
drill finger-lifting $ESDS spb=2,4,8,15
drill pinky-and-index $ESDS spb=2,4,8,15
drill air-bowing spb=4,8,15 bow=normal,reversed
drill parlando $ESDS xpb=1,2,4 first=light,heavy
drill dynamics $ESDS crescendo,decrescendo,pianissimo

# bow changes
drill stationary $ESDS $MFT
drill detache $ESDS $MFTZ rhythms
drill legato $ESDS $MFTZ rhythms
drill martele $ESDS $MFTZ
drill stacatto $ESDS $MFTZ
drill brushing $ESDS $MFTZ
drill spicatto $ESDS $MFTZ
drill colle $ESDS

# bow acceleration
drill fast-bowing $ESDS rest=1,0 bps=1,2
drill speed-changes $ESDS xpb=1,2,3 first=slow,fast

# bow direction
drill overbowing
drill snaking xpb=1,2,3
drill lane-changes lanes=121,232,123,321
drill tilt-flat-tilt $ES

# string crossings
drill single $XING_VARS num=2,3,4
drill double $XING_VARS
drill triple $XING_VARS
drill chords $XING_VARS pat=1-23,12-3,12-23,12-24

# violin hold
cd ..
mcd 5.pitch-arm
drill no-hand-swivels
drill pinky-reaches

# finger independence
drill finger-wiggles straight,curled
drill fingertip-kisses
drill finger-position-jankin
drill finger-position-curls
drill finger-hammers

# finger dropping
drill trills fingers=01,12,23,34,13,24,14 $ES pos=1,3,5,7,9,Z
drill half-scales shape=westside,chicken,gun,porcupine $ES drone=off,on
drill fifth-hops $EF $ES
drill double-stop-trills $ES thirds
drill drop-and-lift-to-harmonic $EF $ES

# vibrato
drill vibrato-knocking fulcrum=wrist,arm loc=air,in-situ silent,voiced
drill on-the-body-vibrato fulcrum=wrist,arm $EF
drill vibrato-slides fulcrum=wrist,arm $ES silent,voiced
drill on-the-string fulcrum=wrist,arm silent,voiced $EF $ES pos=1,3,5,7,9,Z

# shifts
drill one-finger-scales chromatic,major,minor
drill same-finger-shifts $EF int=1,2,3,4,5,6,7,8,9,X,Y,Z pos=1,3,5,7,9,Z
drill different-finger-shifts $EF int=1,2,3,4,5,6,7,8,9,X,Y,Z pos=1,3,5,7,9,Z

# scales
cd ..
mcd 6.both-arms
drillcd chromatic-scale $SCALE_VARS
generate_pattern_scales ud "|G,_A,=A,_B,=B,=C_D|=D_E=E=F_G=G_A|=A_B=B=c_d=d_e|=e=f_g=g_a=a_b|=b_b=a_a=g_g=f=e|_e=d_d=c=B_B=A|_A=G_G=F=E_E=D|_D=C=B,_B,=A,_A,G," 0 1 2 3 4 5
cd ..

drillcd scale-dinosaur $SCALE_VARS
generate_pattern_scales ud "|=G,=A,=B,=C|=D=E^F=G|=A=B=c=d|=e^f=g=a|=g^f=e|=d=c=B=A|=G^F=E=D|=C=B,=A,=G," 1 2
cd ..

drillcd scale-chicken $SCALE_VARS
generate_pattern_scales ud "|=G,=A,=B,=C|=D=E=F=G|=A=B=c=d|=e=f=g=a|=g=f=e|=d=c=B=A|=G=F=E=D|=C=B,=A,=G," 1 2
cd ..

drillcd scale-jake $SCALE_VARS
generate_pattern_scales ud "|=G,=A,_B,=C|=D=E=F=G|=A_B=c=d|=e=f=g=a|=g=f=e|=d=c_B=A|=G=F=E=D|=C_B,=A,=G," 1 2
cd ..

drillcd scale-elwood $SCALE_VARS
generate_pattern_scales ud "|=G,=A,_B,=C|=D_E=F=G|=A_B=c=d|_e=f=g=a|=g=f_e|=d=c_B=A|=G=F_E=D|=C_B,=A,=G," 2
cd ..

drillcd scale-pistol $SCALE_VARS
generate_pattern_scales ud "|=G,_A,_B,=C|=D_E=F=G|_A_B=c=d|_e=f=g_a|=g=f_e|=d=c_B_A|=G=F_E=D|=C_B,_A,=G," 2
cd ..

drillcd scale-nuke $SCALE_VARS
generate_pattern_scales ud "|=G,_A,_B,=C|_D_E=F=G|_A_B=c_d|_e=f=g_a|=g=f_e|_d=c_B_A|=G=F_E_D|=C_B,_A,=G," 2
cd ..

drillcd scale-explosion $SCALE_VARS
generate_pattern_scales ud "|_G,_A,_B,=C|_D_E=F_G|_A_B=c_d|_e=f_g_a|_g=f_e|_d=c_B_A|_G=F_E_D|=C_B,_A,_G," 2
cd ..

cd ..
mkdir 7.phrases
mkdir 8.etudes
mkdir 9.playlist

#chord patterns {301} {es} {3-strings/12, 3-strings/22} {ud} {fmt}
#right hand pizzicato

