#!/bin/bash

INSTRUMENT=116 # woodblock

source drills.lib

PAT=cGEC
generate_tempos metronome/4x64 "
  X:0
  M:4/4
  L:1/4
  Q:100
  K:C
  %%MIDI program $((INSTRUMENT - 1))
  |:$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT:|
  |:$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT:|
  |:$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT:|
  |:$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT:|
  "
generate_tempos metronome/fs.4x4 "
  X:0
  M:4/4
  L:1/4
  Q:100
  K:C
  %%MIDI program $((INSTRUMENT - 1))
  |$PAT|$PAT|$PAT|$PAT|
  Q:50
  |$PAT|$PAT|$PAT|$PAT|
  "

PAT=cGC
generate_tempos metronome/3x64 "
  X:0
  M:3/4
  L:1/4
  Q:100
  K:C
  %%MIDI program $((INSTRUMENT - 1))
  |:$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT:|
  |:$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT:|
  |:$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT:|
  |:$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT:|
  "
generate_tempos metronome/fs.3x4 "
  X:0
  M:3/4
  L:1/4
  Q:100
  K:C
  %%MIDI program $((INSTRUMENT - 1))
  |$PAT|$PAT|$PAT|$PAT|
  Q:50
  |$PAT|$PAT|$PAT|$PAT|
  "

PAT=cC
generate_tempos metronome/2x64 "
  X:0
  M:2/4
  L:1/4
  Q:100
  K:C
  %%MIDI program $((INSTRUMENT - 1))
  |:$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT:|
  |:$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT:|
  |:$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT:|
  |:$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT:|
  "
generate_tempos metronome/fs.2x4 "
  X:0
  M:2/4
  L:1/4
  Q:100
  K:C
  %%MIDI program $((INSTRUMENT - 1))
  |$PAT|$PAT|$PAT|$PAT|
  Q:50
  |$PAT|$PAT|$PAT|$PAT|
  "

PAT=c
generate_tempos metronome/1x64 "
  X:0
  M:1/4
  L:1/4
  Q:100
  K:C
  %%MIDI program $((INSTRUMENT - 1))
  |:$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT:|
  |:$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT:|
  |:$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT:|
  |:$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT|$PAT:|
  "

