#!/bin/bash
#
# generate practise mp3s at different speeds from the midi files
#

INPUT=$HOME/game/create/practise
OUTPUT=$HOME/inbox/practise
INSTRUMENTS=violin
MIDI_INSTRUMENT=0                          # 0: piano, 40: violin, 73: flute, 75: pan flute
AMPLIFICATION=200

for INSTRUMENT in $INSTRUMENTS; do
  for PIECE in $INPUT/$INSTRUMENT/*; do
    for SOURCE in $PIECE/*.mid; do
      NAME=`basename ${SOURCE/.mid/}`
      OUTDIR=$OUTPUT/$INSTRUMENT/`basename $PIECE`/$NAME
      if [ ! -d $OUTDIR ]; then
        mkdir -p $OUTDIR

        TEMPO=125
        COUNTER=01
        while [ $TEMPO -ge 25 ]; do
          timidity $SOURCE --output-24bit -A$AMPLIFICATION -EI$MIDI_INSTRUMENT/1 -T$TEMPO -Ow -o - | avconv -i - $OUTDIR/`printf %02d $COUNTER`-`printf %03d $TEMPO`p.mp3
          COUNTER=$((COUNTER+1))
          TEMPO=$((TEMPO-5))
        done
      fi
    done
  done
done

